name: u_traffic_admin
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  flutter_riverpod: ^2.4.0
  intl: ^0.18.1
  google_fonts: ^6.0.0
  email_validator: ^2.1.17
  quickalert: ^1.0.2
  easy_sidemenu: ^0.5.0
  syncfusion_flutter_datagrid: ^23.1.36
  syncfusion_flutter_core: ^23.1.36
  cached_network_image: ^3.3.0
  syncfusion_flutter_datagrid_export: ^23.1.44
  syncfusion_flutter_xlsio: ^23.1.44
  path_provider: ^2.1.1
  syncfusion_flutter_pdf: ^23.1.44
  firebase_storage: ^11.5.0
  http: ^1.1.0
  image_picker_web: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon/0.75x/app_iconldpi.png
    - assets/app_icon/1.5x/app_iconhdpi.png
    - assets/app_icon/1x/app_iconmdpi.png
    - assets/app_icon/2x/app_iconxhdpi.png
    - assets/app_icon/3x/app_iconxxhdpi.png
    - assets/app_icon/4x/app_iconxxxhdpi.png
    - assets/app_icon/SVG/app_icon.svg
    - assets/logo/app_logo.png
    - assets/logo/logo_color.png
    - assets/logo/logo_white.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
